people:
  trump:
    accounts:
      - TruthTrumpPost
    keywords: []
  musk:
    accounts:
      - elonmusk
    keywords: []

institutions:
  accounts: []
  keywords: []

themes:
  musk_trump:
    keywords: []
    cn_stocks: []
    us_stocks: []
